name: Prettier

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Format
      uses: creyD/prettier_action@v3.3
      with:
        prettier_options: --write **
        commit_message: "Format"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
